apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fang-stock-metrics-data
  namespace: default
  labels:
    app: fang-stock-metrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
