apiVersion: v1
kind: Service
metadata:
  name: fang-stock-metrics
  namespace: default
  labels:
    app: fang-stock-metrics
spec:
  type: NodePort
  selector:
    app: fang-stock-metrics
  ports:
    - port: 8000
      targetPort: metrics
      nodePort: 30800
      name: metrics
